version: "2.4"
services:
  db:
    network_mode: host
    logging:
      driver: none
    container_name: mysite-database
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysite
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    tty: true
    network_mode: host
    restart: on-failure
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend/:/home/python/app/
      - backend_env:/home/python/.local
    ports:
      - "8000:8000"
    environment:
      HOME: /home/python
    command: ["sh", "-c", "./wait-for.sh localhost:3306 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
  frontend:
    tty: true
    network_mode: host
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/:/home/node/app
      - nodemodules:/home/node/app/node_modules
    ports:
      - "3000:3000"
    environment:
      HOME: /home/node
volumes:
  dbdata:
  backend_env:
  nodemodules:
